### PR TITLE
Extend to typer<1.0.0 to match SpaCy

### PR DESCRIPTION
**Pull request by aymenkrifa**
## Description

FastAPI standard (starting from version 0.111.0) added a `fastapi-cli` package that now only supports the `typer` package to be `typer >= 0.12.3`, installing both FastAPI (>=0.111.0) and SpaCy causes a conflict since `weasel`'s Typer version is `0.10.0`
-> Extend the Typer version to `typer<1.0.0` to match `SpaCy`'s version.

### Types of change

Package upgrade 

## Checklist

- [X] I confirm that I have the right to submit this contribution under the project's MIT license.
- [ ] I ran the test suite, and all new and existing tests passed.
- [X] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by svlandeg** [comment]
Thanks! We'll get this fixed.

**Review by svlandeg — APPROVED** [review]

**Comment by svlandeg** [comment]
It looks like the CI is failing because of an unrelated issue, I'll look into that separately first.

**Comment by svlandeg** [comment]
Weasel v0.4.1 is now released!

**Comment by aymenkrifa** [comment]
Awesome, thank you @svlandeg :tada:

**Pull request merged**
