### PR TITLE
Porting explosion/spaCy#12181 solution into weasel

### LINKED ISSUE #66: Error when using a file in a git repository as an asset in spacy projects config
Using a file in a git repository as an asset in a spacy project configuration fails because the code expects only directories.

## How to reproduce the behaviour

Use a file in a git repository as an asset in the `projects.yml` as described in the [documentation](https://spacy.io/usage/projects#data-assets-git):
> path: Path of the **file or directory** to download, relative to the repo root.

Here is a code example trying to use spacy's citation file as an asset:
```yml
assets:
  - dest: "spacy-citation.cff"
    git:
      repo: "https://github.com/explosion/spaCy"
      branch: "master"
      path: "CITATION.cff"
```
Then run `spacy project assets` which fails with the following (reduced) stacktrace:

```
Traceback (most recent call last):
 ...
  File "/venv/lib/python3.8/site-packages/spacy/cli/project/assets.py", line 39, in project_assets_cli
    project_assets(
  File "/venv/lib/python3.8/site-packages/spacy/cli/project/assets.py", line 105, in project_assets
    git_checkout(
  File "/venv/lib/python3.8/site-packages/spacy/cli/_util.py", line 407, in git_checkout
    shutil.copytree(str(source_path), str(dest))
  File "/usr/lib/python3.8/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
NotADirectoryError: [Errno 20] Not a directory: '/tmp/tmpw_23425/CITATION.cff'
```

The reason for the error is that [shutil.copytree](https://docs.python.org/3/library/shutil.html#shutil.copytree) expects a directory and not a single file.

## Your Environment
* Operating System: Ubuntu 20.04
* Python Version Used: 3.8.10
* spaCy Version Used: 3.4.4

### PR DESCRIPTION
**Pull request by jeffrey12cali**
## Description

Resolves #66

I ported the solution from explosion/spaCy#12181 into weasel. Additionally, I have added pytest markers to identify when a test function is related with an issue, like it's set up on the spaCy repo.

### Types of change

Bug fix.

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the test suite, and all new and existing tests passed.
- [x] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Comment by svlandeg** [comment]
Thanks so much for your PR! We'll get this reviewed soonish.

**Comment by jeffrey12cali** [comment]
Sorry, I didn't knew about the pre-commit validation. That's why it failed on the isort module. Now it should pass.

**Comment by jeffrey12cali** [comment]
Please don't run the workflow yet. I noticed that this is not the expected behavior. I'm going to find a workaround for those systems which the permission errors were appearing.

**Review by svlandeg — APPROVED** [review]
Thanks so much! Really appreciate the contribution and attention to detail 🙏 Looks good - we'll get this included in the next `weasel` release (probably soonish).

**Pull request merged**
